# frozen_string_literal: true

source "https://rubygems.org"

gem 'sinatra', '2.2.0'
gem 'sqlite3', '1.4.2'
gem 'rake', '13.0.6'
gem 'sinatra-activerecord', '2.0.25', require: 'sinatra-activerecord'
gem 'activerecord', '6.1.5', require: 'activerecord'
gem 'thin', '1.8.1'